version: '3.8'

services:
  app:
    build:
      args:
        uid: ${uid:-1000}
        user: ${user:-myuser}
        container_project_path: /var/www/html
      context: .
      dockerfile: ./Dockerfile
    container_name: bagisto-app
    restart: always
    ports:
      - "18082:80"
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      APP_URL: http://localhost:18082
      DB_HOST: bagisto-mysql
      DB_DATABASE: first_project
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
      MAIL_HOST: bagisto-mailpit
      MAIL_PORT: 1025
      ELASTICSEARCH_HOST: bagisto-elasticsearch:9200
    depends_on:
      - bagisto-mysql
    networks:
      - bagisto-network
      
  bagisto-mysql:
    image: mysql:8.0
    container_name: bagisto-mysql
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1
    ports:
      - "3307:3306"  
    environment:
      MYSQL_DATABASE: first_project
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bagisto-mysql-data:/var/lib/mysql
    networks:
      - bagisto-network

  bagisto-redis:
    image: redis:6.2-alpine
    container_name: bagisto-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - bagisto-network

  bagisto-phpmyadmin:
    image: phpmyadmin:latest
    container_name: bagisto-phpmyadmin
    restart: always
    environment:
      PMA_HOST: bagisto-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - "18080:80"
    depends_on:
      - bagisto-mysql
    networks:
      - bagisto-network

  bagisto-elasticsearch:
    image: elasticsearch:7.17.0
    container_name: bagisto-elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "19200:9200"
    networks:
      - bagisto-network

  bagisto-kibana:
    image: kibana:7.17.9
    container_name: bagisto-kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://bagisto-elasticsearch:9200
    ports:
      - "15601:5601"
    depends_on:
      - bagisto-elasticsearch
    networks:
      - bagisto-network

  bagisto-mailpit:
    image: axllent/mailpit:latest
    container_name: bagisto-mailpit
    restart: always
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "18025:8025"
    networks:
      - bagisto-network

volumes:
  bagisto-mysql-data:
  redis-data:
  elasticsearch-data:

networks:
  bagisto-network:
    driver: bridge
